#---
#final_name: dummy
#blobstore:
#  provider: s3
#  options:
#    blobstore_path: /tmp/
#min_cli_version: 1.5.0.pre.891
---
final_name: dummy
blobstore:
  provider: s3
  options:
    bucket_name: dummy-release-blobs
